export type TMetricsUpdateAction =
    | 'METRICS_GUEST'
    | 'METRICS_REGISTRATION'
    | 'METRICS_AUTHORIZATION'
    | 'METRICS_PROJECT_CREATION'
    | 'METRICS_TEST_COMPLETION'
    | 'METRICS_TASK_COMPLETION';
