import React, { FC } from 'react';

export const AuthModal: FC = () => (
    <form>
        <input
            type={'text'}
            id={'form-name'}
            name={'form-name'}
            placeholder={'Name:'}
        />
        <input
            type={'text'}
            id={'form-email'}
            name={'form-email'}
            placeholder={'Email:'}
        />
        <input
            type={'text'}
            id={'form-username'}
            name={'form-username'}
            placeholder={'Username:'}
        />
        <input
            type={'text'}
            id={'form-group'}
            name={'form-group'}
            placeholder={'Group:'}
        />
        <textarea
            id={'form-about'}
            name={'form-about'}
            placeholder={'About:'}
        />
        <input
            type={'password'}
            id={'form-password'}
            name={'form-password'}
            placeholder={'Group:'}
        />
        <input
            type={'password'}
            id={'form-password-confirm'}
            name={'form-password-confirm'}
            placeholder={'Group:'}
        />
    </form>
);
